### ISSUE TITLE
Add option to forward SSL 

### ISSUE THREAD

**Issue by lanjelot** [hugsy/proxenet#19]
Add the ability to forward CONNECTs based on regexp (on dest IP or hostname), just like a normal HTTP proxy would do. Sometimes I don't want or can't intercept the SSL traffic to specific hosts (client rejecting proxenet certificate, cert pinning, etc.).
Cheers!

**Comment by hugsy** [comment]
Solved by 825949617bc1f4722ec651bbba590c08ca7a51e5
