### ISSUE TITLE
Can not load any python plugin

### ISSUE THREAD

**Issue by azhai** [hugsy/proxenet#25]
Can not load any python plugin. Only print File 'xxx.py' has not been added.

proxenet v0.4-master:c1b214c
Written by hugsy
Released under: GPLv2
Using library: PolarSSL 1.3.10
Compiled by GNU (Linux-3.10.0-229.1.2.el7.x86_64) with support for :
	[+] 0x00   C               (.so)
	[+] 0x01   Python2.7.5     (.py)
	[+] 0x02   Ruby2.0.0       (.rb)
	[+] 0x03   Perl5.16.3      (.pl)
	[+] 0x04   Lua5.1.4        (.lua)

**Comment by azhai** [comment]
In CentOS 6 amd64
plugin.c:383
if (dir_ptr->d_type != DT_REG)
change to:
if (dir_ptr->d_type != DT_REG && dir_ptr->d_type != DT_UNKNOWN)

**Comment by hugsy** [comment]
I cannot seem to reproduce on a Fedora 20.
Please ensure that the plugins in the `autoload` directory are valid symlinks to the plugins directory. 
See https://github.com/hugsy/proxenet/blob/dev/docs/plugins/index.md#autoload for info.

The fix you provide
```c 
if (dir_ptr->d_type != DT_REG && dir_ptr->d_type != DT_UNKNOWN)
```
will not filter out a lot of cases, as the function would process with unknown file types, which is a behavior to avoid.

What is your file system ? Please provide more details about your configuration.

Thanks

**Comment by hugsy** [comment]
Everything is in the documentation, closing.
