### ISSUE TITLE
ImportError: No module named XXX

### ISSUE THREAD

**Issue by azhai** [hugsy/proxenet#26]
Writing a python plugin in proxenet-plugins/autoload dir,  there is a error when start proxenet,:
ImportError: No module named XXX

The way recommand:
```bash
#First, put the python file XXX.py in proxenet-plugins
cd proxenet-plugins/autoload
mv  XXX.py  ../
#Then, create a symbol link
ln  -s  ../XXX.py  ./
```

**Comment by hugsy** [comment]
This is not a bug but the expected behavior.

Commit 16fc936b189e0ca164a2eb201c7bac8740f151bf added documentation about it.
