### ISSUE TITLE
Add invisible proxy mode

### ISSUE THREAD

**Issue by takeshixx** [hugsy/proxenet#39]
Hi,

it would be nice if proxenet would support an invisible proxy mode for clients that are not proxy-aware. I tried to just implement it in a plugin, but it seems like prexenet runs in circles before the request hits the plugin.

The easiest way for an invisible proxy mode (where requests arrive without a full URI in the first line) would be to grab the target host from the HTTP host header and reconstruct the first line. Here is what I tried in the plugin:

```python
import re

host_header = re.compile(r"Host: (.*)\r\n")
uri_host = re.compile(r"://(.*):")

def proxenet_request_hook(rid, request, uri):
    _uri_host = uri_host.findall(uri)
    _host_header = host_header.findall(request)

    if not _uri_host or not _host_header:
        return request

    uri = uri.replace(_uri_host[0], _host_header[0])
    first, rest = request.split('\r\n', 1)
    request = 'GET {} HTTP/1.1\r\n'.format(uri) + rest

    return request


def proxenet_response_hook(rid, response, uri):
    return response
```

Thanks in advance!

**Comment by hugsy** [comment]
Hi @takeshixx ,

The transparent mode was a feature added some time ago (https://github.com/hugsy/proxenet/issues/20), so I am surprised by your bug report. 

Can you describe how you trying to use proxenet and the environment ?

Thanks for reporting.

**Comment by takeshixx** [comment]
Hi @hugsy,

it seems like the problem was on my side, at least for the plain request. But is there a way to tell proxenet to "forward" such requests with SSL? Like getting a plain request on an arbitrary port and rewrite the first line to HTTPS?

**Comment by takeshixx** [comment]
Unfortunately some (VoIP) vendors don't bother to care a lot about the HTTP standard and set host headers like `Host:10.11.12.13:1234`, with a missing blank after `Host:`. proxenet will fail to find the request header, because of [this line](https://github.com/hugsy/proxenet/blob/c0c3057520f51dc0564f4895d0b462984afd1554/http.c#L173).

I suggest to remove the blank after `Host:` for the sake of versatility. At least that fixed [my problem](https://github.com/takeshixx/proxenet/commit/cb9e5da07c8431285ee940357d69b3f260c2f705).

**Comment by hugsy** [comment]
Hi @takeshixx and thanks for those info.

So the transparent mode is working for you, right? It was simply the `Host` header that failed to be properly recognized by `proxenet`, is that it? If so, I can definitely change that :)

**Comment by takeshixx** [comment]
Hi @hugsy,

yes, that was my problem, with the small change it's working for me now.

Thanks a lot! :)

**Comment by hugsy** [comment]
Awesome, thanks for your feedbacks!
